basePath: /api/v1
definitions:
  github_com_moonx-farm_quote-service_internal_models.GasEstimate:
    properties:
      gasFee:
        type: number
      gasFeeUSD:
        type: number
      gasLimit:
        type: integer
      gasPrice:
        type: number
    type: object
  github_com_moonx-farm_quote-service_internal_models.HealthResponse:
    properties:
      checks:
        additionalProperties:
          type: string
        type: object
      status:
        type: string
      timestamp:
        type: string
      uptime:
        description: Duration as string for swagger compatibility
        type: string
      version:
        type: string
    type: object
  github_com_moonx-farm_quote-service_internal_models.Quote:
    properties:
      callData:
        type: string
      createdAt:
        type: string
      expiresAt:
        type: string
      fromAmount:
        type: number
      fromToken:
        $ref: '#/definitions/github_com_moonx-farm_quote-service_internal_models.Token'
      gasEstimate:
        $ref: '#/definitions/github_com_moonx-farm_quote-service_internal_models.GasEstimate'
      id:
        type: string
      price:
        type: number
      priceImpact:
        type: number
      provider:
        type: string
      route:
        $ref: '#/definitions/github_com_moonx-farm_quote-service_internal_models.Route'
      slippageTolerance:
        type: number
      to:
        type: string
      toAmount:
        type: number
      toAmountMin:
        type: number
      toToken:
        $ref: '#/definitions/github_com_moonx-farm_quote-service_internal_models.Token'
      value:
        type: string
    type: object
  github_com_moonx-farm_quote-service_internal_models.Route:
    properties:
      gasEstimate:
        $ref: '#/definitions/github_com_moonx-farm_quote-service_internal_models.GasEstimate'
      steps:
        items:
          $ref: '#/definitions/github_com_moonx-farm_quote-service_internal_models.RouteStep'
        type: array
      totalFee:
        type: number
    type: object
  github_com_moonx-farm_quote-service_internal_models.RouteStep:
    properties:
      fee:
        type: number
      fromAmount:
        type: number
      fromToken:
        $ref: '#/definitions/github_com_moonx-farm_quote-service_internal_models.Token'
      gasEstimate:
        $ref: '#/definitions/github_com_moonx-farm_quote-service_internal_models.GasEstimate'
      poolAddress:
        type: string
      priceImpact:
        type: number
      protocol:
        type: string
      toAmount:
        type: number
      toToken:
        $ref: '#/definitions/github_com_moonx-farm_quote-service_internal_models.Token'
      type:
        type: string
    type: object
  github_com_moonx-farm_quote-service_internal_models.Token:
    properties:
      address:
        type: string
      chainId:
        type: integer
      change24h:
        type: number
      decimals:
        type: integer
      isNative:
        type: boolean
      lastUpdated:
        type: string
      logoURI:
        type: string
      marketCap:
        type: number
      metadata:
        additionalProperties: true
        type: object
      name:
        type: string
      popular:
        description: Whether token is in popular list
        type: boolean
      priceUSD:
        type: number
      source:
        description: Additional fields for external API integration
        type: string
      symbol:
        type: string
      tags:
        items:
          type: string
        type: array
      verified:
        description: Whether token is verified
        type: boolean
      volume24h:
        type: number
    type: object
  github_com_moonx-farm_quote-service_internal_models.TokenListResponse:
    properties:
      limit:
        type: integer
      metadata:
        additionalProperties: true
        type: object
      page:
        type: integer
      tokens:
        items:
          $ref: '#/definitions/github_com_moonx-farm_quote-service_internal_models.Token'
        type: array
      total:
        type: integer
      updatedAt:
        type: string
    type: object
  internal_handlers.ErrorResponse:
    properties:
      code:
        type: integer
      details: {}
      error:
        type: string
      message:
        type: string
    type: object
host: localhost:3003
info:
  contact:
    email: support@moonxfarm.com
    name: MoonXFarm Team
  description: Quote service for MoonXFarm DEX - Aggregates prices and routes from
    multiple DEX sources
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: MoonXFarm Quote Service API
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Check if the service is running
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_moonx-farm_quote-service_internal_models.HealthResponse'
      summary: Health check
      tags:
      - health
  /quote:
    get:
      consumes:
      - application/json
      description: Get the best quote from all available sources, supports same-chain
        and cross-chain swaps
      parameters:
      - description: Source chain ID
        in: query
        name: fromChainId
        required: true
        type: integer
      - description: Destination chain ID
        in: query
        name: toChainId
        required: true
        type: integer
      - description: Source token address
        in: query
        name: fromToken
        required: true
        type: string
      - description: Destination token address
        in: query
        name: toToken
        required: true
        type: string
      - description: Amount to swap (in token decimals)
        in: query
        name: amount
        required: true
        type: string
      - description: User wallet address
        in: query
        name: userAddress
        type: string
      - description: 'Slippage tolerance (default: 0.5)'
        in: query
        name: slippage
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_moonx-farm_quote-service_internal_models.Quote'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_handlers.ErrorResponse'
      summary: Get best quote
      tags:
      - quotes
  /ready:
    get:
      consumes:
      - application/json
      description: Check if the service is ready to handle requests
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_moonx-farm_quote-service_internal_models.HealthResponse'
        "503":
          description: Service Unavailable
          schema:
            $ref: '#/definitions/github_com_moonx-farm_quote-service_internal_models.HealthResponse'
      summary: Readiness check
      tags:
      - health
  /tokens/search:
    get:
      consumes:
      - application/json
      description: Search tokens by name, symbol, or address with intelligent chain-based
        prioritization
      parameters:
      - description: Search query (name, symbol, or address)
        in: query
        name: q
        required: true
        type: string
      - description: Preferred chain ID for prioritization
        in: query
        name: chainId
        type: integer
      - description: 'Maximum results (default: 20, max: 100)'
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_moonx-farm_quote-service_internal_models.TokenListResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/internal_handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/internal_handlers.ErrorResponse'
      summary: Search tokens
      tags:
      - tokens
schemes:
- http
- https
swagger: "2.0"
